### ISSUE TITLE
Make Initial Script executable in vcs

### ISSUE THREAD

**Issue by thorsummoner** [mthxx/Budget#36]
Basically, rename `Budget,py` to just `Budget` and make it executable (`chmod +x Budget`). (Or better yet, `budget`).

Also consider creating a `Budget.desktop` file with an icon associated for desktop-launching; the find of file that would be installed into your start menu in the stable release.

**Comment by mthxx** [comment]
I did start work on a setup.py [https://github.com/mthxx/Budget/blob/master/setup.py] as well as a bit of research into packaging it up for Ubuntu/Debian systems and submitting it to the AUR. I'll create separate issues for each.
