### ISSUE TITLE
Logo/Icon

### ISSUE THREAD

**Issue by mthxx** [mthxx/Budget#63]
The logo needs to be swapped out with the new svg logo.

**Comment by mthxx** [comment]
Works on Arch. Doesn't work on Fedora or Ubuntu. No idea why at the moment.

**Comment by cassidyjames** [comment]
Where are you installing your icons? I know for elementary OS (and I believe Ubuntu) we expect them to be in `/usr/share/icons/hicolor`

**Comment by mthxx** [comment]
I've currently got it installing to "/usr/share/icons/hicolor/scalable/apps/". Here's the relevant file. https://github.com/mthxx/Budget/blob/master/setup.py

I'm currently using a single svg image rather than multiple pixel perfect which I was thinking might be the problem, but I haven't tested that theory yet.

**Comment by thorsummoner** [comment]
I believe you can drop svgs in each resolution and they should work, eg you
don't need to rasterize them, just to tell the system this svg works at
this size

**Comment by mthxx** [comment]
So this is very weird behavior. I am dropping svg's in each directory for 16, 24, 32, 48, 64, and 128. Running Gnome (Arch), it did not pick up on the icon until I also dropped it in the scalable folder.
Running Gnome (Fedora) and Unity (Ubuntu), it did not pick up any of the images.

I am starting to this the problem lies in my .desktop file.

**Comment by cassidyjames** [comment]
The .desktop looks fine so long as your icons are named, `budget.svg` or `budget.png`...

**Comment by mthxx** [comment]
I just tried them as PNG's. Same results across the board.
I also just now tested it on KDE (Arch) and it worked just fine. I'll have to spin up a few more VM's later to try it out on different configurations, but clearly I am missing something.

**Comment by thorsummoner** [comment]
I'm pretty confused by how I haven't ever found good documentation on how
to setup icons on Linux, especially icon packs, I've never found any tools
to "compile" source svgs into the correct directory structure, and I don't
want to believe their assembled by hand still these days.

**Comment by cassidyjames** [comment]
@thorsummoner I just filed a bug against the elementary OS developer guide at https://github.com/elementary/mvp/issues/786 ;)

**Comment by mthxx** [comment]
Well, I have a workaround for the moment. I've hard coded the path "/usr/share/icons/hicolor/scalable/apps/budget.svg" in the .desktop file. This is not a very good solution though, it is completely ignoring the correctly sized icons for the various views, and also makes it so that users with alternative icons packs in use will be forced to see stock version of the icon. Closing this ticket, but creating a new one (see #76) to fix the hard coding.

**Comment by mthxx** [comment]
@cassidyjames: The solution to this issue might be relevant to your documentation. I completely resolved this and #76 by also adding the icons to the "Adwaita" folder, in addition to the hicolor folder. Both Ubuntu (Unity) and Fedora (Gnome) picked up the icons immediately in their launchers.
